data = open(r"f:\开发软件项目文件\对练社交\knowledge_base\extra_course_cards.js","rb").read()
print(f"Raw bytes: {len(data)}")
print(f"Has \\r: {b'\\r' in data}")
print(f"Has \\n: {b'\\n' in data}")
print(f"CRLF count: {data.count(b'\\r\\n')}")
print(f"LF count: {data.count(b'\\n')}")
print(f"Lines: {len(data.split(b'\\n'))}")
print()
print(repr(data[:200]))