module.exports = {
  port: process.env.PORT || 3000,
  env: process.env.NODE_ENV || 'development',
  jwt: {
    secret: process.env.JWT_SECRET || 'dev-secret',
    expiresIn: process.env.JWT_EXPIRES_IN || '7d',
  },
  llm: {
    providers: {
      deepseek: {
        apiKey: process.env.DEEPSEEK_API_KEY,
        baseUrl: process.env.DEEPSEEK_BASE_URL || 'https://api.deepseek.com/v1',
        model: process.env.DEEPSEEK_MODEL || 'deepseek-chat',
        maxTokens: 1024,
        temperature: 0.7,
        enabled: true,
        priority: 10,
      },
      openai: {
        apiKey: process.env.OPENAI_API_KEY,
        baseUrl: process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1',
        model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
        maxTokens: 1024,
        temperature: 0.7,
        enabled: true,
        priority: 9,
      },
      gemini: {
        apiKey: process.env.GEMINI_API_KEY,
        baseUrl: process.env.GEMINI_BASE_URL || 'https://generativelanguage.googleapis.com/v1beta',
        model: process.env.GEMINI_MODEL || 'gemini-1.5-flash',
        maxTokens: 1024,
        temperature: 0.7,
        enabled: true,
        priority: 8,
      },
      anthropic: {
        apiKey: process.env.ANTHROPIC_API_KEY,
        baseUrl: process.env.ANTHROPIC_BASE_URL || 'https://api.anthropic.com/v1',
        model: process.env.ANTHROPIC_MODEL || 'claude-3-haiku-20240307',
        maxTokens: 1024,
        temperature: 0.7,
        enabled: true,
        priority: 7,
      },
      moonshot: {
        apiKey: process.env.MOONSHOT_API_KEY,
        baseUrl: process.env.MOONSHOT_BASE_URL || 'https://api.moonshot.cn/v1',
        model: process.env.MOONSHOT_MODEL || 'moonshot-v1-8k',
        maxTokens: 1024,
        temperature: 0.7,
        enabled: true,
        priority: 6,
      },
      qwen: {
        apiKey: process.env.QWEN_API_KEY,
        baseUrl: process.env.QWEN_BASE_URL || 'https://dashscope.aliyuncs.com/api/v1',
        model: process.env.QWEN_MODEL || 'qwen-plus',
        maxTokens: 1024,
        temperature: 0.7,
        enabled: true,
        priority: 5,
      },
      zhipu: {
        apiKey: process.env.ZHIPU_API_KEY,
        baseUrl: process.env.ZHIPU_BASE_URL || 'https://open.bigmodel.cn/api/paas/v4',
        model: process.env.ZHIPU_MODEL || 'glm-4',
        maxTokens: 1024,
        temperature: 0.7,
        enabled: true,
        priority: 4,
      },
      huggingface: {
        apiKey: process.env.HUGGINGFACE_API_KEY,
        baseUrl: process.env.HUGGINGFACE_BASE_URL || 'https://api-inference.huggingface.co/models',
        model: process.env.HUGGINGFACE_MODEL || 'Qwen/Qwen2-7B-Instruct',
        maxTokens: 512,
        temperature: 0.7,
        enabled: true,
        priority: 3,
      },
      perplexity: {
        apiKey: process.env.PERPLEXITY_API_KEY,
        baseUrl: process.env.PERPLEXITY_BASE_URL || 'https://api.perplexity.ai',
        model: process.env.PERPLEXITY_MODEL || 'llama-3-sonar-small-32k-online',
        maxTokens: 1024,
        temperature: 0.7,
        enabled: true,
        priority: 2,
      },
      ollama: {
        apiKey: null,
        baseUrl: process.env.OLLAMA_BASE_URL || 'http://localhost:11434',
        model: process.env.OLLAMA_MODEL || 'qwen2.5:14b',
        maxTokens: 1024,
        temperature: 0.7,
        enabled: true,
        priority: 1,
      },
    },
  },
};