const fs=require('fs'),path=require('path');
const source='G:\\BaiduNetdiskDownload\\高情商话术\\高情商话术\\580好好接话电子版\\好好接话txt版.txt';
const raw=fs.readFileSync(source,'utf8').replace(/^\uFEFF/,'').replace(/\r/g,''); const lines=raw.split('\n');
const chapterRe=/^第([一二三四五六七八九十百]+)章/; const lessonRe=/^\s*\d+[．\.、]\s*(.+)$/; const summaryRe=/^五分钟速记本章重点/;
const tocTitles=[]; const tocSeen=new Set(); for(const line of lines.slice(0,320)){const m=line.match(chapterRe); if(m&&!/\d+[．\.、]/.test(line)&&!tocSeen.has(m[1])){tocTitles.push(line.trim());tocSeen.add(m[1]);}}
const bodyStart=lines.findIndex((line,i)=>i>250&&/^第一章/.test(line)); const bodyEndRaw=lines.findIndex((line,i)=>i>bodyStart&&/^第一章.*\d+[．\.、]/.test(line)); const bodyLines=lines.slice(bodyStart,bodyEndRaw<0?lines.length:bodyEndRaw);
const chapters=[]; let chapter=null,lesson=null,chapterNo=0; function cleanTitle(v){return String(v).replace(/^\s*\d+[．\.、]\s*/,'').trim();} function cleanChapterTitle(v){return String(v).replace(/^第.+章[　\\s]*/,'').trim();} function finishLesson(){if(!lesson)return; lesson.content=lesson.content.join('\n').replace(/^\n+|\n+$/g,''); chapter.lessons.push(lesson); lesson=null;} function finishChapter(){finishLesson();if(chapter){chapter.intro=chapter.intro.join('\n').replace(/^\n+|\n+$/g,'');chapter.summary=chapter.summary.join('\n').replace(/^\n+|\n+$/g,'');chapters.push(chapter);}chapter=null;}
for(const line of bodyLines){const cm=line.match(chapterRe);if(cm){finishChapter();chapterNo++;chapter={title:tocTitles[chapterNo-1]||line.trim(),rawMarker:line.trim(),lessons:[],intro:[],summary:[],summaryMode:false};continue;}if(!chapter)continue;if(summaryRe.test(line)){finishLesson();chapter.summaryMode=true;continue;}const lm=line.match(lessonRe);if(lm&&!chapter.summaryMode){finishLesson();lesson={title:cleanTitle(lm[1]),content:[]};continue;}if(chapter.summaryMode)chapter.summary.push(line);else if(lesson)lesson.content.push(line);else chapter.intro.push(line);}finishChapter();
const cards=[];let n=0;
function addCard(kind,title,content,ch){if(!content)return; n++; const chapterLabel=cleanChapterTitle(ch.title); const kindLabel=kind==='lesson'?'原始课程正文':(kind==='intro'?'章节导语原文':'章节速记原文'); cards.push({id:'raw_hhjh_'+String(n).padStart(3,'0'),kind,title,scene:'好好接话 · '+chapterLabel,category:'好好接话课程',content,rawText:content,principle:kindLabel+'，逐字保留；请结合上下文理解和练习。',tips:['好好接话',chapterLabel,kindLabel],practicePrompt:kind==='lesson'?'阅读并练习“'+title+'”，再用自己的话完成一次表达。':(kind==='intro'?'先阅读本章导语，再进入各小技能课程。':'用本章速记复习关键方法，并选择一项进行练习。'),userEmotion:[],coachStyle:[],level:kind==='lesson'?'课程原文':'课程辅助',round:n,tags:['好好接话',chapterLabel,kind,title],source:source,safetyNote:'这是原始课程学习材料，请结合真实情境使用，尊重对方边界，不编造、不施压。'});}
for(const ch of chapters){addCard('intro','章节导语 · '+cleanChapterTitle(ch.title),ch.intro,ch);for(const l of ch.lessons)addCard('lesson',l.title,l.content,ch);addCard('summary','章节速记 · '+cleanChapterTitle(ch.title),ch.summary,ch);}
fs.writeFileSync('knowledge_base/raw_course_cards.js','/* Generated from 好好接话txt版.txt; each body skill is one lesson, chapter intro/summary are auxiliary cards. */\nwindow.rawCourseLearningCards='+JSON.stringify(cards)+';\n','utf8'); console.log(JSON.stringify({cards:cards.length,lessons:chapters.reduce((n,c)=>n+c.lessons.length,0),auxiliary:cards.filter(c=>c.kind!=='lesson').length,chars:cards.reduce((n,c)=>n+c.content.length,0)}));