(function(){
 var KEY='duilian_profile';
 function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
 function persona(){return read().user_persona||{}}
 function mapping(p){var m={'销售与客户沟通':['客户投诉应对','4S店砍价','谈判协商技巧'],'面试求职':['模拟面试','面试后的感谢信'],'工作汇报':['向上汇报被质疑','演讲发言技巧'],'日常社交':['兴趣社群自我介绍','社交聚会破冰'],'公开演讲':['公共演讲技巧','演讲发言技巧'],'短视频/直播':['社交媒体运营','视频会议沟通'],'综合提升表达':['兴趣社群自我介绍','模拟面试'],'其他/还不确定':['兴趣社群自我介绍']};return m[p.target_scenario]||m['综合提升表达']}
 function choose(){var p=persona(),names=mapping(p),all=(window.trainingScenes||[]).concat(window.customScenes||[]);for(var i=0;i<names.length;i++){var found=all.find(function(s){return s&&s.name===names[i]});if(found)return found}return all.find(function(s){return s&&s.name==='兴趣社群自我介绍'})||all.find(function(s){return s})||null}
 function label(p,scene){var scenario=p.target_scenario||'综合提升表达',pain=(p.pain_point||'一开口就紧张').split('，')[0],occupation=p.occupation?(' · '+p.occupation):'';return '因为你选择了【'+scenario+'】和【'+pain+'】，推荐从【'+(scene?scene.name:'30秒开场练习')+'】开始'+occupation}
 window.showPersonalizedRecommendation=function(){var p=persona(),scene=choose();if(scene){scene.unlocked=true;if(typeof userData==='object'){userData.hasSelectedInitial=true;userData.userPersona=p;userData.onboardingCompleted=true}if(typeof coachMemory==='object'){coachMemory.userPreferences=coachMemory.userPreferences||{};coachMemory.userPreferences.userPersona=p;coachMemory.userPreferences.personalizationContext='目标：'+(p.target_scenario||'综合提升表达')+'；痛点：'+(p.pain_point||'一开口就紧张')+'；职业：'+(p.occupation||'未填写');if(typeof saveUserData==='function')saveUserData()}if(typeof saveData==='function')saveData();try{localStorage.setItem('duilian_personalized_recommendation',JSON.stringify({sceneId:scene.id,sceneName:scene.name,text:label(p,scene),persona:p,createdAt:Date.now()}))}catch(e){}var name=document.getElementById('last-training-name'),desc=document.getElementById('last-training-desc'),btn=document.getElementById('continue-training-btn');if(name)name.textContent=label(p,scene);if(desc)desc.textContent='首节练习会根据你的痛点采用'+(p.pain_point&&p.pain_point.indexOf('发音')>=0?'语音跟读':p.pain_point&&p.pain_point.indexOf('重点')>=0?'结构化公式':'低压力跟练')+'方式。';if(btn){btn.textContent='开始专属练习';btn.onclick=function(){startTraining(scene.id)}}if(typeof renderHome==='function')renderHome();if(typeof showToast==='function')showToast('已匹配：'+scene.name)}else if(typeof showToast==='function')showToast('暂时没有找到匹配课程，请先进入训练中心选择')} 
 window.getPersonalizedRecommendedScene=function(){return choose()};
})();

